# Generated by Django 3.0.6 on 2020-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200911_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FilePathField(default='/img/tba.png', path='/img'),
        ),
    ]
