# Generated by Django 3.0.6 on 2020-09-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200913_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='technology',
        ),
    ]
